version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      day: "sunday"
    target-branch: "main"
    reviewers:
      - "core"
  # ignore npm packages from sample
  - package-ecosystem: "nuget"
    directory: "/samples/"
    schedule:
      interval: "monthly"
    labels: [ ]
    ignore:
      - dependency-name: "*"