<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
	  <ProjectReference Include="..\JuntosSomosMais.Ziggurat\JuntosSomosMais.Ziggurat.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MongoDB.Driver" />
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>JuntosSomosMais.Ziggurat.MongoDB.Tests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

</Project>
